<a href="https://colab.research.google.com/github/Leenayesh/Leenayesh.github.io/blob/main/Chart1Extensions.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import requests

In [26]:
countries = ["SSF"]

In [27]:
data=[]
for country in countries:
  url='https://api.worldbank.org/v2/country/'+country+'/indicator/SH.STA.SUIC.FE.P5?format=json'
  json_data=requests.get(url).json()[1]
  data.append(json_data)
  print (url)

https://api.worldbank.org/v2/country/SSF/indicator/SH.STA.SUIC.FE.P5?format=json

In [28]:
import numpy as np
import pandas as pd

In [29]:
flat_data=np.array(data).flatten()

In [30]:
df=pd.json_normalize(flat_data)
df
df=df.dropna()
df

   countryiso3code  date  ...  country.id       country.value
1              SSF  2019  ...          ZG  Sub-Saharan Africa
2              SSF  2018  ...          ZG  Sub-Saharan Africa
3              SSF  2017  ...          ZG  Sub-Saharan Africa
4              SSF  2016  ...          ZG  Sub-Saharan Africa
5              SSF  2015  ...          ZG  Sub-Saharan Africa
6              SSF  2014  ...          ZG  Sub-Saharan Africa
7              SSF  2013  ...          ZG  Sub-Saharan Africa
8              SSF  2012  ...          ZG  Sub-Saharan Africa
9              SSF  2011  ...          ZG  Sub-Saharan Africa
10             SSF  2010  ...          ZG  Sub-Saharan Africa
11             SSF  2009  ...          ZG  Sub-Saharan Africa
12             SSF  2008  ...          ZG  Sub-Saharan Africa
13             SSF  2007  ...          ZG  Sub-Saharan Africa
14             SSF  2006  ...          ZG  Sub-Saharan Africa
15             SSF  2005  ...          ZG  Sub-Saharan Africa
16             SSF  2004  ...          ZG  Sub-Saharan Africa
17             SSF  2003  ...          ZG  Sub-Saharan Africa
18             SSF  2002  ...          ZG  Sub-Saharan Africa
19             SSF  2001  ...          ZG  Sub-Saharan Africa
20             SSF  2000  ...          ZG  Sub-Saharan Africa

[20 rows x 10 columns]

In [31]:
df.to_csv('Projectchart1extension2.csv')

In [32]:
data=[]
for country in countries:
  url='https://api.worldbank.org/v2/country/'+country+'/indicator/SP.DYN.TO65.FE.ZS?format=json'
  json_data=requests.get(url).json()[1]
  data.append(json_data)
  print (url)

https://api.worldbank.org/v2/country/SSF/indicator/SP.DYN.TO65.FE.ZS?format=json

In [33]:
flat_data=np.array(data).flatten()
df1=pd.json_normalize(flat_data)
df1=df1.dropna()
df1

   countryiso3code  date  ...  country.id       country.value
1              SSF  2019  ...          ZG  Sub-Saharan Africa
2              SSF  2018  ...          ZG  Sub-Saharan Africa
3              SSF  2017  ...          ZG  Sub-Saharan Africa
4              SSF  2016  ...          ZG  Sub-Saharan Africa
5              SSF  2015  ...          ZG  Sub-Saharan Africa
6              SSF  2014  ...          ZG  Sub-Saharan Africa
7              SSF  2013  ...          ZG  Sub-Saharan Africa
8              SSF  2012  ...          ZG  Sub-Saharan Africa
9              SSF  2011  ...          ZG  Sub-Saharan Africa
10             SSF  2010  ...          ZG  Sub-Saharan Africa
11             SSF  2009  ...          ZG  Sub-Saharan Africa
12             SSF  2008  ...          ZG  Sub-Saharan Africa
13             SSF  2007  ...          ZG  Sub-Saharan Africa
14             SSF  2006  ...          ZG  Sub-Saharan Africa
15             SSF  2005  ...          ZG  Sub-Saharan Africa
16             SSF  2004  ...          ZG  Sub-Saharan Africa
17             SSF  2003  ...          ZG  Sub-Saharan Africa
18             SSF  2002  ...          ZG  Sub-Saharan Africa
19             SSF  2001  ...          ZG  Sub-Saharan Africa
20             SSF  2000  ...          ZG  Sub-Saharan Africa
21             SSF  1999  ...          ZG  Sub-Saharan Africa
22             SSF  1998  ...          ZG  Sub-Saharan Africa
23             SSF  1997  ...          ZG  Sub-Saharan Africa
24             SSF  1996  ...          ZG  Sub-Saharan Africa
25             SSF  1995  ...          ZG  Sub-Saharan Africa
26             SSF  1994  ...          ZG  Sub-Saharan Africa
27             SSF  1993  ...          ZG  Sub-Saharan Africa
28             SSF  1992  ...          ZG  Sub-Saharan Africa
29             SSF  1991  ...          ZG  Sub-Saharan Africa
30             SSF  1990  ...          ZG  Sub-Saharan Africa
31             SSF  1989  ...          ZG  Sub-Saharan Africa
32             SSF  1988  ...          ZG  Sub-Saharan Africa
33             SSF  1987  ...          ZG  Sub-Saharan Africa
34             SSF  1986  ...          ZG  Sub-Saharan Africa
35             SSF  1985  ...          ZG  Sub-Saharan Africa
36             SSF  1984  ...          ZG  Sub-Saharan Africa
37             SSF  1983  ...          ZG  Sub-Saharan Africa
38             SSF  1982  ...          ZG  Sub-Saharan Africa
39             SSF  1981  ...          ZG  Sub-Saharan Africa
40             SSF  1980  ...          ZG  Sub-Saharan Africa
41             SSF  1979  ...          ZG  Sub-Saharan Africa
42             SSF  1978  ...          ZG  Sub-Saharan Africa
43             SSF  1977  ...          ZG  Sub-Saharan Africa
44             SSF  1976  ...          ZG  Sub-Saharan Africa
45             SSF  1975  ...          ZG  Sub-Saharan Africa
46             SSF  1974  ...          ZG  Sub-Saharan Africa
47             SSF  1973  ...          ZG  Sub-Saharan Africa
48             SSF  1972  ...          ZG  Sub-Saharan Africa
49             SSF  1971  ...          ZG  Sub-Saharan Africa

[49 rows x 10 columns]

In [34]:
df1.to_csv('Projectchart1extension1.csv')

In [19]:
data=[]
for country in countries:
  url='https://api.worldbank.org/v2/country/'+country+'/indicator/SL.EMP.MPYR.FE.ZS?format=json'
  json_data=requests.get(url).json()[1]
  data.append(json_data)
  print (url)

https://api.worldbank.org/v2/country/SSF/indicator/SL.EMP.MPYR.FE.ZS?format=json

In [35]:
flat_data=np.array(data).flatten()
df2=pd.json_normalize(flat_data)
df2=df2.dropna()
df2

   countryiso3code  date  ...  country.id       country.value
1              SSF  2019  ...          ZG  Sub-Saharan Africa
2              SSF  2018  ...          ZG  Sub-Saharan Africa
3              SSF  2017  ...          ZG  Sub-Saharan Africa
4              SSF  2016  ...          ZG  Sub-Saharan Africa
5              SSF  2015  ...          ZG  Sub-Saharan Africa
6              SSF  2014  ...          ZG  Sub-Saharan Africa
7              SSF  2013  ...          ZG  Sub-Saharan Africa
8              SSF  2012  ...          ZG  Sub-Saharan Africa
9              SSF  2011  ...          ZG  Sub-Saharan Africa
10             SSF  2010  ...          ZG  Sub-Saharan Africa
11             SSF  2009  ...          ZG  Sub-Saharan Africa
12             SSF  2008  ...          ZG  Sub-Saharan Africa
13             SSF  2007  ...          ZG  Sub-Saharan Africa
14             SSF  2006  ...          ZG  Sub-Saharan Africa
15             SSF  2005  ...          ZG  Sub-Saharan Africa
16             SSF  2004  ...          ZG  Sub-Saharan Africa
17             SSF  2003  ...          ZG  Sub-Saharan Africa
18             SSF  2002  ...          ZG  Sub-Saharan Africa
19             SSF  2001  ...          ZG  Sub-Saharan Africa
20             SSF  2000  ...          ZG  Sub-Saharan Africa
21             SSF  1999  ...          ZG  Sub-Saharan Africa
22             SSF  1998  ...          ZG  Sub-Saharan Africa
23             SSF  1997  ...          ZG  Sub-Saharan Africa
24             SSF  1996  ...          ZG  Sub-Saharan Africa
25             SSF  1995  ...          ZG  Sub-Saharan Africa
26             SSF  1994  ...          ZG  Sub-Saharan Africa
27             SSF  1993  ...          ZG  Sub-Saharan Africa
28             SSF  1992  ...          ZG  Sub-Saharan Africa
29             SSF  1991  ...          ZG  Sub-Saharan Africa
30             SSF  1990  ...          ZG  Sub-Saharan Africa
31             SSF  1989  ...          ZG  Sub-Saharan Africa
32             SSF  1988  ...          ZG  Sub-Saharan Africa
33             SSF  1987  ...          ZG  Sub-Saharan Africa
34             SSF  1986  ...          ZG  Sub-Saharan Africa
35             SSF  1985  ...          ZG  Sub-Saharan Africa
36             SSF  1984  ...          ZG  Sub-Saharan Africa
37             SSF  1983  ...          ZG  Sub-Saharan Africa
38             SSF  1982  ...          ZG  Sub-Saharan Africa
39             SSF  1981  ...          ZG  Sub-Saharan Africa
40             SSF  1980  ...          ZG  Sub-Saharan Africa
41             SSF  1979  ...          ZG  Sub-Saharan Africa
42             SSF  1978  ...          ZG  Sub-Saharan Africa
43             SSF  1977  ...          ZG  Sub-Saharan Africa
44             SSF  1976  ...          ZG  Sub-Saharan Africa
45             SSF  1975  ...          ZG  Sub-Saharan Africa
46             SSF  1974  ...          ZG  Sub-Saharan Africa
47             SSF  1973  ...          ZG  Sub-Saharan Africa
48             SSF  1972  ...          ZG  Sub-Saharan Africa
49             SSF  1971  ...          ZG  Sub-Saharan Africa

[49 rows x 10 columns]

In [36]:
df2.to_csv('Projectchart1extension3.csv')